# colors for fuzzel application launcher
# You can use this template by adding the following to wallust.toml:
# fuzzel = { template = "fuzzel.ini", target = "~/.config/fuzzel/colors.ini" }
# and add the following to your foot.ini config
#
# [main]
# include=/home/USERNAME/.config/fuzzel/colors.ini


[colors]
background=#010101ff
text=#F5F5F5ff
prompt=#010202ff
placeholder=#545454ff
input=#757575ff
match=#7E7E7Eff
selection=#9C9C9Cff
selection-text=#BFBFBFff
selection-match=#E8E8E8ff
counter=#F2F2F2ff
border=#9C9C9Cff

