# Wallust colors for Hyprland
$background = rgba(010101ff)
$foreground = rgba(F5F5F5ff)

$color0 = rgba(010202ff)
$color1 = rgba(545454ff)
$color2 = rgba(757575ff)
$color3 = rgba(7E7E7Eff)
$color4 = rgba(9C9C9Cff)
$color5 = rgba(BFBFBFff)
$color6 = rgba(E8E8E8ff)
$color7 = rgba(F2F2F2ff)

general {
    col.active_border = $color4
    col.inactive_border = $color1
}

decoration {
    shadow {
        enabled = true
        range = 4
        render_power = 3
        color = $background
    }
}
