wallpaper {
  monitor = eDP-1
  path = /home/sebasp/Imagenes/wallpaper_mountains.png
  fit_mode = cover
}

wallpaper {
  monitor = HDMI-A-1
  path = /home/sebasp/Imagenes/wallpaper_mountains.png
  fit_mode = cover
}

wallpaper {
  monitor = DVI-I-1
  path = /home/sebasp/Imagenes/wallpaper_mountains.png
  fit_mode = cover
}
